import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto_Mono } from 'next/font/google';
import { Providers } from './providers';
import type { Metadata } from 'next';
import { Navigation } from '../components';

import Image from 'next/image';
import logo from './logoPlane.svg';
import style from './layout.module.scss';

export const metadata: Metadata = {
   title: 'Test Tickets',
   description: 'Generated by create next app',
};

const roboto = Roboto_Mono({
   subsets: ['latin'],
   display: 'swap',
});

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en" className={roboto.className}>
         <body className={style.App}>
            <div className={style.logoContainer}>
               <Image src={logo} width={30} height={30} alt="logo" />
            </div>
            <AppRouterCacheProvider options={{ key: 'scss', enableCssLayer: true }}>
               <Providers>
                  <Navigation />
                  <main>{children}</main>
               </Providers>
            </AppRouterCacheProvider>
         </body>
      </html>
   );
}
