import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import Link from '@mui/material/Link';
import Image from 'next/image';
import logo from './logoPlane.svg';
import style from './layout.module.scss';
import './globals.css';

export const metadata: Metadata = {
   title: 'Test Tickets',
   description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={style.App}>
            <div className={style.logoContainer}>
               <Image src={logo} width={30} height={30} alt="logo" />
            </div>
            <AppRouterCacheProvider options={{ key: 'scss', enableCssLayer: true }}>
               <nav className={style.linkContainer}>
                  <Link href="/home">Home</Link>
                  <Link href="/search">Search</Link>
               </nav>
               <main>{children}</main>
            </AppRouterCacheProvider>
         </body>
      </html>
   );
}
